### PR TITLE
Update to 1.1.0

### PR DESCRIPTION
**Pull request by cbrueffer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cbrueffer** [comment]
@conda-forge-admin please rerender

**Comment by brendanf** [comment]
I'm traveling right now but I will try to address this.

**Comment by brendanf** [comment]
@cbrueffer What actually is the easiest way for me to add to this pull request?  I have generated new patch files which apply correctly and, at least on my own Linux computer, result in a successful build.

**Comment by cbrueffer** [comment]
Thanks for checking @brendanf , maybe just easiest to open a new PR and we close this one.

**Comment by cbrueffer** [comment]
Closed in favour of https://github.com/conda-forge/r-nanonext-feedstock/pull/7

**Pull request closed without merging**
